package jsound.exceptions.codes;

public enum ErrorCodes {
    CLI_ERROR_CODE("JSND0001"),
    INVALID_SCHEMA_EXCEPTION("JSND0002"),
    RUNTIME_EXCEPTION_ERROR_CODE("XPDY0130"),
    UNEXPECTED_TYPE_EXCEPTION("XPTY0004"),

    MISSING_KIND("JDST0001"),
    TYPE_NOT_RESOLVED("JDST0002"),
    INVALID_KIND("JDST0003"),
    INCONSISTENT_NAME("JDST0004"),
    LESS_RESTRICTIVE_FACET("JDST0005"),
    INVALID_ENUM_VALUE("JDST0006"),
    BASETYPE_INCOSISTENT_WITH_KIND("JDST0007"),
    MISSING_NAME_OR_TYPE_OBJECT_CONTENT("JDST0008"),
    CLOSED_SET_BACK_TO_FALSE("JDST0009"),
    CLOSED_NOT_RESPECTED("JDST0010"),
    REQUIRED_SET_BACK_TO_FALSE("JDST0011"),
    UNIONTYPE_USED_AS_ANNOTATION("JDST0012"),
    OVERRIDE_BUILTIN_TYPES("JDST0013"),
    ALREADY_EXISTING_TYPE("JDST0014"),
    INSTANCE_NOT_VALID_AGAINST_SCHEMA("JDST0015"),
    ANNOTATE_WITH_UNKNOWN_TYPE("JDST0016"),
    NOT_VALID_WHEN_ANNOTATING("JDST0017"),
    CYCLE_IN_BASETYPE("JDST0018");

    private final String errorCode;

    ErrorCodes(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }
}
