package org.jsound.facets;

public enum FacetTypes {
    LENGTH,
    MIN_LENGTH,
    MAX_LENGTH,
    MIN_INCLUSIVE,
    MAX_INCLUSIVE,
    MIN_EXCLUSIVE,
    MAX_EXCLUSIVE,
    TOTAL_DIGITS,
    FRACTION_DIGITS,
    EXPLICIT_TIMEZONE,

    CONTENT,
    CLOSED,

    ENUMERATION,
    METADATA,
    CONSTRAINTS
}
